### ISSUE TITLE
Error, cannot play the game

### ISSUE THREAD

**Issue by gyeoarf** [ObjectJosh/Singify#2]
![image](https://github.com/user-attachments/assets/139a122c-3919-41dd-aaf7-707781c4ec82)

All the dependencies are installed as well as homebrew; spotify client id and client secret are good as well; tried while playing something with spotify and not playing anything. 
When playing something, it pauses the song but then does the error.

**Comment by ObjectJosh** [comment]
Hi @gyeoarf `sp.call(['say', text])` (the subprocess call `say`) is native to MacOS, so it won't work on linux. You could probably use `pyttsx3` instead for it to work with your OS. Something like:
```
import pyttsx3

...

def say(text: str) -> None:
    engine = pyttsx3.init()
    engine.say(text)
    engine.runAndWait()
    
...
```
